/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateLoggingConfigurationRequest
 */
public class CreateLoggingConfigurationRequestTest {
    private final CreateLoggingConfigurationRequest model = new CreateLoggingConfigurationRequest();

    /**
     * Model tests for CreateLoggingConfigurationRequest
     */
    @Test
    public void testCreateLoggingConfigurationRequest() {
        // TODO: test CreateLoggingConfigurationRequest
    }

    /**
     * Test the property 'logGroupArn'
     */
    @Test
    public void logGroupArnTest() {
        // TODO: test logGroupArn
    }

    /**
     * Test the property 'clientToken'
     */
    @Test
    public void clientTokenTest() {
        // TODO: test clientToken
    }

}
