/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DescribeAlertManagerDefinitionResponseAlertManagerDefinition;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DescribeAlertManagerDefinitionResponse
 */
public class DescribeAlertManagerDefinitionResponseTest {
    private final DescribeAlertManagerDefinitionResponse model = new DescribeAlertManagerDefinitionResponse();

    /**
     * Model tests for DescribeAlertManagerDefinitionResponse
     */
    @Test
    public void testDescribeAlertManagerDefinitionResponse() {
        // TODO: test DescribeAlertManagerDefinitionResponse
    }

    /**
     * Test the property 'alertManagerDefinition'
     */
    @Test
    public void alertManagerDefinitionTest() {
        // TODO: test alertManagerDefinition
    }

}
