/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListWorkspacesResponse
 */
public class ListWorkspacesResponseTest {
    private final ListWorkspacesResponse model = new ListWorkspacesResponse();

    /**
     * Model tests for ListWorkspacesResponse
     */
    @Test
    public void testListWorkspacesResponse() {
        // TODO: test ListWorkspacesResponse
    }

    /**
     * Test the property 'workspaces'
     */
    @Test
    public void workspacesTest() {
        // TODO: test workspaces
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

}
