/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.CreateLoggingConfigurationResponseStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoggingConfigurationMetadata
 */
public class LoggingConfigurationMetadataTest {
    private final LoggingConfigurationMetadata model = new LoggingConfigurationMetadata();

    /**
     * Model tests for LoggingConfigurationMetadata
     */
    @Test
    public void testLoggingConfigurationMetadata() {
        // TODO: test LoggingConfigurationMetadata
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'workspace'
     */
    @Test
    public void workspaceTest() {
        // TODO: test workspace
    }

    /**
     * Test the property 'logGroupArn'
     */
    @Test
    public void logGroupArnTest() {
        // TODO: test logGroupArn
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'modifiedAt'
     */
    @Test
    public void modifiedAtTest() {
        // TODO: test modifiedAt
    }

}
