/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RuleGroupsNamespaceStatusCode
 */
public class RuleGroupsNamespaceStatusCodeTest {
    /**
     * Model tests for RuleGroupsNamespaceStatusCode
     */
    @Test
    public void testRuleGroupsNamespaceStatusCode() {
        // TODO: test RuleGroupsNamespaceStatusCode
    }

}
