/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents the output of a DescribeRuleGroupsNamespace operation.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:08:28.126488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DescribeRuleGroupsNamespaceResponse {
  public static final String SERIALIZED_NAME_RULE_GROUPS_NAMESPACE = "ruleGroupsNamespace";
  @SerializedName(SERIALIZED_NAME_RULE_GROUPS_NAMESPACE)
  @javax.annotation.Nonnull
  private DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace ruleGroupsNamespace;

  public DescribeRuleGroupsNamespaceResponse() {
  }

  public DescribeRuleGroupsNamespaceResponse ruleGroupsNamespace(@javax.annotation.Nonnull DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace ruleGroupsNamespace) {
    this.ruleGroupsNamespace = ruleGroupsNamespace;
    return this;
  }

  /**
   * Get ruleGroupsNamespace
   * @return ruleGroupsNamespace
   */
  @javax.annotation.Nonnull
  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace getRuleGroupsNamespace() {
    return ruleGroupsNamespace;
  }

  public void setRuleGroupsNamespace(@javax.annotation.Nonnull DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace ruleGroupsNamespace) {
    this.ruleGroupsNamespace = ruleGroupsNamespace;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeRuleGroupsNamespaceResponse describeRuleGroupsNamespaceResponse = (DescribeRuleGroupsNamespaceResponse) o;
    return Objects.equals(this.ruleGroupsNamespace, describeRuleGroupsNamespaceResponse.ruleGroupsNamespace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ruleGroupsNamespace);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeRuleGroupsNamespaceResponse {\n");
    sb.append("    ruleGroupsNamespace: ").append(toIndentedString(ruleGroupsNamespace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ruleGroupsNamespace");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ruleGroupsNamespace");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DescribeRuleGroupsNamespaceResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DescribeRuleGroupsNamespaceResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DescribeRuleGroupsNamespaceResponse is not found in the empty JSON string", DescribeRuleGroupsNamespaceResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DescribeRuleGroupsNamespaceResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DescribeRuleGroupsNamespaceResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DescribeRuleGroupsNamespaceResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `ruleGroupsNamespace`
      DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.validateJsonElement(jsonObj.get("ruleGroupsNamespace"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DescribeRuleGroupsNamespaceResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DescribeRuleGroupsNamespaceResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DescribeRuleGroupsNamespaceResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DescribeRuleGroupsNamespaceResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<DescribeRuleGroupsNamespaceResponse>() {
           @Override
           public void write(JsonWriter out, DescribeRuleGroupsNamespaceResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DescribeRuleGroupsNamespaceResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DescribeRuleGroupsNamespaceResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DescribeRuleGroupsNamespaceResponse
   * @throws IOException if the JSON string is invalid with respect to DescribeRuleGroupsNamespaceResponse
   */
  public static DescribeRuleGroupsNamespaceResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DescribeRuleGroupsNamespaceResponse.class);
  }

  /**
   * Convert an instance of DescribeRuleGroupsNamespaceResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

