/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.CreateRuleGroupsNamespaceResponseStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:08:28.126488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace {
  public static final String SERIALIZED_NAME_ARN = "arn";
  @SerializedName(SERIALIZED_NAME_ARN)
  @javax.annotation.Nonnull
  private String arn;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private CreateRuleGroupsNamespaceResponseStatus status;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nonnull
  private String data;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime modifiedAt;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Map tags;

  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace() {
  }

  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace arn(@javax.annotation.Nonnull String arn) {
    this.arn = arn;
    return this;
  }

  /**
   * Get arn
   * @return arn
   */
  @javax.annotation.Nonnull
  public String getArn() {
    return arn;
  }

  public void setArn(@javax.annotation.Nonnull String arn) {
    this.arn = arn;
  }


  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace status(@javax.annotation.Nonnull CreateRuleGroupsNamespaceResponseStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public CreateRuleGroupsNamespaceResponseStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull CreateRuleGroupsNamespaceResponseStatus status) {
    this.status = status;
  }


  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace data(@javax.annotation.Nonnull String data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nonnull
  public String getData() {
    return data;
  }

  public void setData(@javax.annotation.Nonnull String data) {
    this.data = data;
  }


  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace modifiedAt(@javax.annotation.Nonnull OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
    return this;
  }

  /**
   * Get modifiedAt
   * @return modifiedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }

  public void setModifiedAt(@javax.annotation.Nonnull OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace tags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public Map getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace describeRuleGroupsNamespaceResponseRuleGroupsNamespace = (DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace) o;
    return Objects.equals(this.arn, describeRuleGroupsNamespaceResponseRuleGroupsNamespace.arn) &&
        Objects.equals(this.name, describeRuleGroupsNamespaceResponseRuleGroupsNamespace.name) &&
        Objects.equals(this.status, describeRuleGroupsNamespaceResponseRuleGroupsNamespace.status) &&
        Objects.equals(this.data, describeRuleGroupsNamespaceResponseRuleGroupsNamespace.data) &&
        Objects.equals(this.createdAt, describeRuleGroupsNamespaceResponseRuleGroupsNamespace.createdAt) &&
        Objects.equals(this.modifiedAt, describeRuleGroupsNamespaceResponseRuleGroupsNamespace.modifiedAt) &&
        Objects.equals(this.tags, describeRuleGroupsNamespaceResponseRuleGroupsNamespace.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arn, name, status, data, createdAt, modifiedAt, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace {\n");
    sb.append("    arn: ").append(toIndentedString(arn)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("arn");
    openapiFields.add("name");
    openapiFields.add("status");
    openapiFields.add("data");
    openapiFields.add("createdAt");
    openapiFields.add("modifiedAt");
    openapiFields.add("tags");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("arn");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("data");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("modifiedAt");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace is not found in the empty JSON string", DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `arn`
      String.validateJsonElement(jsonObj.get("arn"));
      // validate the required field `name`
      String.validateJsonElement(jsonObj.get("name"));
      // validate the required field `status`
      CreateRuleGroupsNamespaceResponseStatus.validateJsonElement(jsonObj.get("status"));
      // validate the required field `data`
      String.validateJsonElement(jsonObj.get("data"));
      // validate the required field `createdAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("createdAt"));
      // validate the required field `modifiedAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("modifiedAt"));
      // validate the optional field `tags`
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("tags"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.class));

       return (TypeAdapter<T>) new TypeAdapter<DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace>() {
           @Override
           public void write(JsonWriter out, DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace
   * @throws IOException if the JSON string is invalid with respect to DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace
   */
  public static DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace.class);
  }

  /**
   * Convert an instance of DescribeRuleGroupsNamespaceResponseRuleGroupsNamespace to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

