/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.CreateAlertManagerDefinitionResponseStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DescribeAlertManagerDefinitionResponseAlertManagerDefinition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:08:28.126488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DescribeAlertManagerDefinitionResponseAlertManagerDefinition {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private CreateAlertManagerDefinitionResponseStatus status;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nonnull
  private String data;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime modifiedAt;

  public DescribeAlertManagerDefinitionResponseAlertManagerDefinition() {
  }

  public DescribeAlertManagerDefinitionResponseAlertManagerDefinition status(@javax.annotation.Nonnull CreateAlertManagerDefinitionResponseStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public CreateAlertManagerDefinitionResponseStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull CreateAlertManagerDefinitionResponseStatus status) {
    this.status = status;
  }


  public DescribeAlertManagerDefinitionResponseAlertManagerDefinition data(@javax.annotation.Nonnull String data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nonnull
  public String getData() {
    return data;
  }

  public void setData(@javax.annotation.Nonnull String data) {
    this.data = data;
  }


  public DescribeAlertManagerDefinitionResponseAlertManagerDefinition createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public DescribeAlertManagerDefinitionResponseAlertManagerDefinition modifiedAt(@javax.annotation.Nonnull OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
    return this;
  }

  /**
   * Get modifiedAt
   * @return modifiedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }

  public void setModifiedAt(@javax.annotation.Nonnull OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeAlertManagerDefinitionResponseAlertManagerDefinition describeAlertManagerDefinitionResponseAlertManagerDefinition = (DescribeAlertManagerDefinitionResponseAlertManagerDefinition) o;
    return Objects.equals(this.status, describeAlertManagerDefinitionResponseAlertManagerDefinition.status) &&
        Objects.equals(this.data, describeAlertManagerDefinitionResponseAlertManagerDefinition.data) &&
        Objects.equals(this.createdAt, describeAlertManagerDefinitionResponseAlertManagerDefinition.createdAt) &&
        Objects.equals(this.modifiedAt, describeAlertManagerDefinitionResponseAlertManagerDefinition.modifiedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, data, createdAt, modifiedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeAlertManagerDefinitionResponseAlertManagerDefinition {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("data");
    openapiFields.add("createdAt");
    openapiFields.add("modifiedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("data");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("modifiedAt");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DescribeAlertManagerDefinitionResponseAlertManagerDefinition
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DescribeAlertManagerDefinitionResponseAlertManagerDefinition.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DescribeAlertManagerDefinitionResponseAlertManagerDefinition is not found in the empty JSON string", DescribeAlertManagerDefinitionResponseAlertManagerDefinition.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DescribeAlertManagerDefinitionResponseAlertManagerDefinition.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DescribeAlertManagerDefinitionResponseAlertManagerDefinition` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DescribeAlertManagerDefinitionResponseAlertManagerDefinition.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `status`
      CreateAlertManagerDefinitionResponseStatus.validateJsonElement(jsonObj.get("status"));
      // validate the required field `data`
      String.validateJsonElement(jsonObj.get("data"));
      // validate the required field `createdAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("createdAt"));
      // validate the required field `modifiedAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("modifiedAt"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DescribeAlertManagerDefinitionResponseAlertManagerDefinition.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DescribeAlertManagerDefinitionResponseAlertManagerDefinition' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DescribeAlertManagerDefinitionResponseAlertManagerDefinition> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DescribeAlertManagerDefinitionResponseAlertManagerDefinition.class));

       return (TypeAdapter<T>) new TypeAdapter<DescribeAlertManagerDefinitionResponseAlertManagerDefinition>() {
           @Override
           public void write(JsonWriter out, DescribeAlertManagerDefinitionResponseAlertManagerDefinition value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DescribeAlertManagerDefinitionResponseAlertManagerDefinition read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DescribeAlertManagerDefinitionResponseAlertManagerDefinition given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DescribeAlertManagerDefinitionResponseAlertManagerDefinition
   * @throws IOException if the JSON string is invalid with respect to DescribeAlertManagerDefinitionResponseAlertManagerDefinition
   */
  public static DescribeAlertManagerDefinitionResponseAlertManagerDefinition fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DescribeAlertManagerDefinitionResponseAlertManagerDefinition.class);
  }

  /**
   * Convert an instance of DescribeAlertManagerDefinitionResponseAlertManagerDefinition to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

