/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents the output of a ListRuleGroupsNamespaces operation.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:08:28.126488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ListRuleGroupsNamespacesResponse {
  public static final String SERIALIZED_NAME_RULE_GROUPS_NAMESPACES = "ruleGroupsNamespaces";
  @SerializedName(SERIALIZED_NAME_RULE_GROUPS_NAMESPACES)
  @javax.annotation.Nonnull
  private List ruleGroupsNamespaces;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "nextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public ListRuleGroupsNamespacesResponse() {
  }

  public ListRuleGroupsNamespacesResponse ruleGroupsNamespaces(@javax.annotation.Nonnull List ruleGroupsNamespaces) {
    this.ruleGroupsNamespaces = ruleGroupsNamespaces;
    return this;
  }

  /**
   * Get ruleGroupsNamespaces
   * @return ruleGroupsNamespaces
   */
  @javax.annotation.Nonnull
  public List getRuleGroupsNamespaces() {
    return ruleGroupsNamespaces;
  }

  public void setRuleGroupsNamespaces(@javax.annotation.Nonnull List ruleGroupsNamespaces) {
    this.ruleGroupsNamespaces = ruleGroupsNamespaces;
  }


  public ListRuleGroupsNamespacesResponse nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListRuleGroupsNamespacesResponse listRuleGroupsNamespacesResponse = (ListRuleGroupsNamespacesResponse) o;
    return Objects.equals(this.ruleGroupsNamespaces, listRuleGroupsNamespacesResponse.ruleGroupsNamespaces) &&
        Objects.equals(this.nextToken, listRuleGroupsNamespacesResponse.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ruleGroupsNamespaces, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListRuleGroupsNamespacesResponse {\n");
    sb.append("    ruleGroupsNamespaces: ").append(toIndentedString(ruleGroupsNamespaces)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ruleGroupsNamespaces");
    openapiFields.add("nextToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ruleGroupsNamespaces");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListRuleGroupsNamespacesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListRuleGroupsNamespacesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListRuleGroupsNamespacesResponse is not found in the empty JSON string", ListRuleGroupsNamespacesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListRuleGroupsNamespacesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListRuleGroupsNamespacesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ListRuleGroupsNamespacesResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `ruleGroupsNamespaces`
      List.validateJsonElement(jsonObj.get("ruleGroupsNamespaces"));
      // validate the optional field `nextToken`
      if (jsonObj.get("nextToken") != null && !jsonObj.get("nextToken").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("nextToken"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListRuleGroupsNamespacesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListRuleGroupsNamespacesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListRuleGroupsNamespacesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListRuleGroupsNamespacesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ListRuleGroupsNamespacesResponse>() {
           @Override
           public void write(JsonWriter out, ListRuleGroupsNamespacesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListRuleGroupsNamespacesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListRuleGroupsNamespacesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListRuleGroupsNamespacesResponse
   * @throws IOException if the JSON string is invalid with respect to ListRuleGroupsNamespacesResponse
   */
  public static ListRuleGroupsNamespacesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListRuleGroupsNamespacesResponse.class);
  }

  /**
   * Convert an instance of ListRuleGroupsNamespacesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

