/*
 * Amazon Prometheus Service
 * Amazon Managed Service for Prometheus
 *
 * The version of the OpenAPI document: 2020-08-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * State of a workspace.
 */
@JsonAdapter(WorkspaceStatusCode.Adapter.class)
public enum WorkspaceStatusCode {
  
  CREATING("CREATING"),
  
  ACTIVE("ACTIVE"),
  
  UPDATING("UPDATING"),
  
  DELETING("DELETING"),
  
  CREATION_FAILED("CREATION_FAILED");

  private String value;

  WorkspaceStatusCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WorkspaceStatusCode fromValue(String value) {
    for (WorkspaceStatusCode b : WorkspaceStatusCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WorkspaceStatusCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final WorkspaceStatusCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WorkspaceStatusCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WorkspaceStatusCode.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    WorkspaceStatusCode.fromValue(value);
  }
}

